# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations

import ielex.lexicon.models as models

import json


def forwards_func(apps, schema_editor):
    LanguageList = apps.get_model('lexicon', 'LanguageList')
    LanguageList.objects.create(
        name=models.LanguageList.BLANK,
        description="Autogenerated blank language list.")


def reverse_func(apps, schema_editor):
    LanguageList = apps.get_model('lexicon', 'LanguageList')
    LanguageList.objects.filter(name=models.LanguageList.BLANK).delete()


class Migration(migrations.Migration):

    dependencies = [('lexicon', '0061_remove_languagelist_data')]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
