# -*- coding: utf-8 -*-
# Inspired by:
# https://github.com/lingdb/CoBL/issues/223#issuecomment-256815113
from __future__ import unicode_literals, print_function
from django.db import migrations


data = {'nose': 'While fighting, he hit him in the nose. (Kassian)',
        'dirty': 'This cup is clean and that one is dirty.',
        'red': 'Blood is red.',
        'white': 'There is a white cloud in the sky.',
        'breathe': "People can't breathe underwater. ",
        'live': 'How many years can people live for?',
        'fight': 'The two men are fighting outside.',
        'flower': 'What type of flower is this?',
        'stone': 'He held the stone in his hand',
        'near': "You can walk there in one day; it's near.",
        'smooth': 'He picked a smooth stone from the river.',
        'fruit': 'He picked fruit from the trees.',
        'sand': 'She let the sand fall through her hands.',
        'know': 'They know that we are coming.',
        'far': "You can't walk there in one day; it's too far.",
        'rain': 'I saw him standing in the rain.',
        'tooth': 'You can break a tooth while eating hard food. (Kassian)',
        'bone': 'He fell and broke a bone.',
        'ear': 'One ear of his was bigger than the other ear. ',
        'two': 'One plus one is two.',
        'right': 'He is blind in his right eye.',
        'blow': 'He blew on the sticks to start the fire.',
        'eye': 'She closed one eye.',
        'mother': 'Everyone has a father and a mother.',
        'push': 'He was pushing and pulling the furniture around the room.  ',
        'sit': 'He is sitting over there.',
        'many': 'We picked many (a lot of) '
                '(insert name of local fruit) today.',
        'freeze': 'When water freezes, it becomes ice. ',
        'skin': 'His skin was old and hard.',
        'moon': 'I saw the moon in the sky.',
        'back': 'I fell over and now my back hurts.',
        'knee': 'He put his hand on his knee.',
        'child': 'That is their first child.',
        'navel': 'One could see his navel.',
        'louse': 'I picked a louse from his hair.',
        'cry': 'She was crying when I saw her.',
        'run': 'Can you run fast?',
        'three': 'Three plus one is four.',
        'name': 'What is your name?',
        'root': 'You could see some of the roots '
                'of the tree above the ground.',
        'wash': 'She washed her hands.',
        'carry': 'She carried her bag (under her arm).',
        'what': 'What are you eating?',
        'forest': 'There are many animals in the forest.',
        'dry': 'Is it dry or wet?',
        'old': 'He lives in the old house, not in the new house.',
        'all': 'He has cut down all the trees.',
        'sew': 'He sewed the two pieces of cloth together.',
        'fall': 'I fell from the tree yesterday and hurt my back.',
        'wipe': 'He wiped the sweat from his brow.',
        'few': "It's a small village. There are few houses. "
               "(Eng. There are not many houses.)",
        'smoke': 'I could see the smoke from the fire.',
        'sun': "During the day, the sun is in the sky; at night, it's not.",
        'hide': 'They hid their food from the animal.',
        'cut': "I've cut my finger; look, it's bleeding.",
        'die': 'Everyone dies sooner or later.',
        'lake': 'Her house is beside the lake.',
        'sky': 'There were white clouds in the blue sky.',
        'sing': 'I heard him yesterday. He was singing.',
        'there': 'The knife is (over) there.',
        'scratch': 'She scratched her head.',
        'hold': 'He is holding a stick in his hand.',
        'stand': 'He is standing over there.',
        'river': 'He lives beside the river.',
        'cloud': 'There were white clouds in the blue sky. (WOLD)',
        'egg': "Don't drop the egg; it will break!",
        'burn': 'The wood is burning in the fire.',
        'not': 'I do not understand.',
        'foot': 'Her foot is injured so she cannot walk.',
        'hunt': 'He is hunting animals in the forest.',
        'tail': 'The dog wagged its tail.',
        'dog': 'I would like to own a dog.',
        'stab': 'I stabbed him in the belly (with a knife).',
        'yesterday': "I haven't seen him today but I saw him yesterday.",
        'black': 'Charcoal is black.',
        'fat': 'Cut the fat off the meat.',
        'person': 'Only one person at a time can pass through the gate.',
        'mouth': 'He put his fingers in his mouth.',
        'drink': 'He drank because he was thirsty.',
        'sea': 'Her house is beside the sea.',
        'water': 'She was thirsty, so she drank some water.',
        'ash': 'There was nothing left but ash.',
        'man': 'I saw a man and a woman.',
        'some': 'There are some (insert name of local fruit) in the basket',
        'if': 'If she does this, then it will happen.',
        'play': 'They are playing a game outside.',
        'sweet': 'This apple is ripe now, it tastes sweet.',
        'big': 'This is a big stone. That is a small stone.',
        'thick': 'That tree trunk is thick; '
                 'it would take a long time cut through.',
        'turn': 'It was heavy so it was hard to turn it.',
        'how': 'How do you make fire?',
        'wet': 'Is it wet or dry?',
        'fish': 'I can see a fish swimming in the water.',
        'spit': 'He spat on the ground.',
        'eat': 'Eat some food and drink some water.',
        'this': 'I used this knife.',
        'vomit': 'He ate something bad and threw up (vomited).',
        'chest': 'His wore a medal on his chest.',
        'squeeze': "Don't squeeze the ball - you'll burst it!",
        'flow': 'The river flows, e.g. past the village, to the sea etc.',
        'fear': 'While the dog was here, I was scared.',
        'green': 'The grass was fresh and green.',
        'do': 'What did you **do** in the village yesterday?',
        'see': 'I see him every day on the road.',
        'hard': 'It was very hard. When he bit it he broke his tooth.',
        'bite': 'The dog bit him.',
        'guts': 'He cut open the animal and pulled out its guts.',
        'rotten': 'That (insert name of local fruit) is rotten.',
        'bad': 'That is a bad idea.',
        'swell': 'His arm swelled after he was injured.',
        'round': 'That table is round.',
        'in': 'The dog is in a basket.',
        'float': 'The leaf is floating on the river.',
        'bark': 'He tore some bark off the tree.',
        'here': 'The knife is here.',
        'narrow': 'Here the river is narrow; further down it is wide.',
        'that': 'I used that knife.',
        'year': 'The year is almost over.',
        'throw': 'He threw a stick into the water.',
        'pull': 'He was pushing and pulling the furniture around the room.  ',
        'hit': 'He hit the ball with the stick.',
        'wind': 'She felt the wind in her face.',
        'when': 'When will we meet again?',
        'wide': "The canyon is wide here, but further down it's narrow.",
        'yellow': 'The natural color of egg yolk. (midday sun?)',
        'small': 'This is a small stone. That is a big stone.',
        'leg': 'He fell and broke his leg.',
        'hand': 'He burned his hand.',
        'stick': 'He carried a stick under his arm.',
        'dig': 'He is digging in the ground.',
        'house': 'His house is at the edge of the village.',
        'woman': 'I saw a man and a woman.',
        'tie': 'He tied the two sticks together.',
        'belly': 'He punched him in the belly.',
        'kill': 'They started fighting. He killed him.',
        'snake': 'He jumped when he saw the snake.',
        'short': 'This is a short rope; that is a long rope.',
        'claw': 'It caught its prey in its claws.',
        'rub': 'He rubbed his belly.',
        'fly_N': 'He killed a fly.',
        'take': 'Take the money when you go.',
        'thigh': 'He slapped his thigh.',
        'feather': 'What bird does this feather come from?',
        'shadow': 'He could see his shadow on the ground.',
        'four': 'Four plus one is five.',
        'and': 'I can see a tree and a rock.',
        'earth': 'As he dug the hole, he threw out the earth.',
        'grind': 'He is grinding flour.',
        'leaf': 'He picked a leaf from the tree.',
        'head': 'He has lots of hair on his head.',
        'day': 'Day and night.',
        'hear': 'I heard a noise last night.',
        'at': 'He stopped at the rock half way to the village.',
        'heavy': 'The rock was very heavy.',
        'star': 'There were many stars in the night sky.',
        'who': 'Who killed this dog? (Kassian)',
        'say': 'She said that she would be late.',
        'one': 'One plus one is two.',
        'left': 'He is blind in his left eye.',
        'thin': 'This piece of wood is thin, and that one is thick.',
        'where': 'Where is the knife?',
        'nail': 'He had very long nails on his fingers.',
        'tree': 'There is a tree beside the house.',
        'count': 'I counted the stones; there were five stones.',
        'wing': 'Birds have wings; people do not.',
        'other': 'He opened one eye and kept the other eye closed.',
        'give': 'She wanted to cut the (insert name of local fruit). '
                'He gave her a knife.',
        'full': 'An empty pot is easier to carry than a full pot. (WOLD)',
        'hot': 'The stone is hot (warm) under the sun.',
        'smell': 'I (can) smell smoke.',
        'tongue': 'He stuck his tongue out.',
        'horn': 'Some animals have horns. Humans do not.',
        'bitter': 'The leaves tasted bitter.',
        'neck': 'He put his hand on his neck.',
        'night': 'Night and day.',
        'lie': 'She was lying on the ground.',
        'walk': 'People can walk but fish cannot.',
        'meat': 'What animal does this meat come from?',
        'seed': 'You can eat the seeds of (insert name of local fruit).',
        'fire': 'He was cold, so he moved closer to the fire.',
        'laugh': 'When I saw him, he was laughing.',
        'snow': 'There was snow on the ground.',
        'grass': 'There is grass growing beside the river.',
        'blood': 'Blood is red.',
        'worm': 'There is a worm in this (insert name of local fruit).',
        'new': 'He lives in the new house; not in the old house.',
        'come': "I saw him on the road. "
                "I don't know where he was coming from.",
        'mountain': 'He started to climb the mountain.',
        'bird': 'What bird does this feather come from?',
        'hair': 'She pulled him by his hair. (almost Kassian)',
        'five': 'Four plus one is five.',
        'long': 'This is a long rope; that is a short rope.',
        'fly_V': 'Birds can fly but people cannot. (close to Kassian)',
        'father': 'Everyone has a father and a mother.',
        'swim': 'He is swimming in the lake.',
        'true': 'The story he is telling is true.',
        'good': 'That is a good idea.',
        'sleep': 'He is sleeping in the house.',
        'straight': 'This stick is straight, but that one is bent.',
        'fog': "I couldn't see the village because of the fog.",
        'sharp': 'A sharp knife cuts better than a blunt one.',
        'think': "What are you doing?  I'm just thinking.",
        'dust': 'When the ground is dry, you kick up dust when you walk.'}


def forwards_func(apps, schema_editor):
    Meaning = apps.get_model("lexicon", "Meaning")

    for gloss, exampleContext in data.iteritems():
        try:
            entry = Meaning.objects.get(gloss=gloss)
            entry.exampleContext = exampleContext
            entry.save()
        except Meaning.DoesNotExist:
            print('\nCould not set exampleContext for Meaning: %s' % gloss)


def reverse_func(apps, schema_editor):
    print('Reverse of 0123_fill_meaning_examplecontext')


class Migration(migrations.Migration):

    dependencies = [('lexicon', '0122_meaning_examplecontext')]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
