# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 10:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0132_swap_transliteration_orthographic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lexeme',
            old_name='transliteration',
            new_name='nativeScript',
        ),
    ]
