# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0146_clean_lexeme_romanised_3'),
    ]

    operations = [
        migrations.CreateModel(
            name='RomanisedSymbol',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('lastTouched', models.DateTimeField(auto_now=True)),
                ('lastEditedBy', models.CharField(
                    default='unknown', max_length=32)),
                ('symbol', models.CharField(max_length=8)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
