# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0151_normalize_romanised'),
    ]

    operations = [
        migrations.AddField(
            model_name='meaning',
            name='ixElicitation',
            field=models.IntegerField(default=0),
        ),
    ]
