# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-04-24 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0156_language_nativescriptisrtl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='notInExport',
            field=models.BooleanField(default=1),
        ),
    ]
