# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0138_auto_20161220_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='nexusexport',
            name='description',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
