# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0139_auto_20161220_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='ENTRYTYPE',
            field=models.CharField(choices=[('book', 'book'),
                                            ('article', 'article'),
                                            ('expert', 'expert'),
                                            ('online', 'online'),
                                            ('inbook', 'inbook'),
                                            ('misc', 'misc')],
                                   max_length=32),
        ),
    ]
