# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0140_auto_20161221_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='part',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
