# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-04 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0152_meaning_ixelicitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='nexusexport',
            name='_exportTableData',
            field=models.BinaryField(null=True),
        ),
    ]
