# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensional_semantics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semanticextensioncitation',
            name='reliability',
            field=models.CharField(choices=[
                ('A', 'High'),
                ('B', 'Good (e.g. should be double checked)'),
                ('C', 'Doubtful'),
                ('L', 'Loanword'),
                ('X', 'Exclude (e.g. not the Swadesh term)')], max_length=1),
        ),
    ]
