# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 11:31
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('extensional_semantics', '0002_auto_20161213_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semanticdomain',
            name='relation_ids',
            field=models.CharField(
                blank=True,
                max_length=999,
                validators=[django.core.validators.RegexValidator(
                    re.compile('^\\d+(?:\\,\\d+)*\\Z', 32),
                    code='invalid',
                    message='Enter only digits separated by commas.')]),
        ),
    ]
